"""A tiny synthetic decision domain, so RLCD can be trained and audited end to end.

Every state is a support ticket assembled from sentence templates; the outcome is
generated by a fixed rule, so the probabilities the model reports can be compared
against real outcomes. Templates are split into disjoint train and shift sets so
that the calibration report also shows what distribution shift does to ECE.
"""

from __future__ import annotations

import random
from dataclasses import dataclass

from .schema import DecisionSample

PAYMENT_SENTENCES = [
    "The payout to the customer's bank was rejected by the processor.",
    "The card was declined twice for insufficient funds.",
    "The bank transfer was returned and the payout is still pending.",
    "The refund never arrived and the ledger shows a failed payout.",
    "The payment processor flagged the transaction as a chargeback.",
]
PAYMENT_SHIFT = [
    "The settlement report shows an unallocated transfer that never landed.",
    "The customer's direct deposit bounced and the balance was rolled back.",
    "A debit reversal appeared after the disbursement window closed.",
]
ACCOUNT_SENTENCES = [
    "The customer cannot log in and the password reset email never arrived.",
    "Two-factor authentication codes are rejected on every device.",
    "The account was locked after too many sign-in attempts.",
    "The login page shows an expired session for this user.",
    "The user was signed out and cannot complete account recovery.",
]
ACCOUNT_SHIFT = [
    "The identity provider keeps returning an invalid credential assertion.",
    "The session token is not surviving the redirect after authentication.",
    "The user's device fingerprints no longer match the enrolled set.",
]
OTHER_SENTENCES = [
    "The customer asked whether the pricing page lists annual discounts.",
    "The user wants to know where the mobile app stores its theme setting.",
    "The customer asked for a copy of the marketing brochure.",
]
OTHER_SHIFT = [
    "The customer enquired about the font used in the onboarding slides.",
    "The user asked which colour the dashboard uses for archived items.",
]
URGENT_SENTENCES = [
    "The customer says they will raise a chargeback with their bank today.",
    "The customer has threatened legal action and named their regulator.",
    "The account is under an active fraud investigation.",
    "The customer says they will close the account this week.",
]
URGENT_SHIFT = [
    "The customer has engaged external counsel and set a deadline of Friday.",
    "A payment-network dispute was opened against the merchant account today.",
    "The customer escalated the matter to a consumer protection body.",
]
NEUTRAL_SENTENCES = [
    "The customer has been with the platform for four years.",
    "This is the third message in the thread.",
    "The ticket was opened on a weekday morning.",
    "The customer prefers email over phone.",
    "The account has a verified email address.",
]

QUEUE_OPTIONS = {
    "payments": "Payout failures and payment processing",
    "account": "Login and account access",
    "other": "Something else",
}
ESCALATION_OPTIONS = {"yes": "Yes", "no": "No"}


#: Kept as a name for the synthetic generator's samples.
Sample = DecisionSample


def _pick(pool: list[str], shift: bool, rng: random.Random) -> str:
    return rng.choice(pool)


def sample_state(
    rng: random.Random,
    *,
    shift: bool = False,
    ambiguous_probability: float = 0.25,
    extra_sentences: int = 2,
) -> tuple[str, str, bool]:
    """Return ``(state, queue_label, urgent)`` for one synthetic ticket."""

    pay = PAYMENT_SHIFT if shift else PAYMENT_SENTENCES
    acc = ACCOUNT_SHIFT if shift else ACCOUNT_SENTENCES
    oth = OTHER_SHIFT if shift else OTHER_SENTENCES
    urg = URGENT_SHIFT if shift else URGENT_SENTENCES

    queue = rng.choice(["payments", "account", "other"])
    primary = {"payments": pay, "account": acc, "other": oth}[queue]

    sentences: list[str] = []
    if rng.random() < ambiguous_probability:
        # A competing symptom, plus an explicit marker on the deciding clause: the
        # task stays well defined, but the readout has to notice the marker.
        competing_pool = {"payments": acc, "account": pay, "other": pay}[queue]
        sentences.append(rng.choice(competing_pool))
        sentences.append("Primary issue: " + rng.choice(primary))
    else:
        sentences.append(rng.choice(primary))
    for _ in range(extra_sentences):
        sentences.append(rng.choice(NEUTRAL_SENTENCES))

    urgent = rng.random() < 0.35
    if urgent:
        sentences.append(rng.choice(urg))
    rng.shuffle(sentences)
    return " ".join(sentences), queue, urgent


def generate(n: int, *, seed: int = 0, shift: bool = False, question: str = "queue") -> list[Sample]:
    rng = random.Random(seed)
    samples: list[Sample] = []
    for _ in range(n):
        state, queue, urgent = sample_state(rng, shift=shift)
        if question == "queue":
            samples.append(Sample(state=state, question_id="queue", target=queue))
        elif question == "escalate":
            samples.append(
                Sample(state=state, question_id="escalate", target="yes" if urgent else "no")
            )
        else:
            raise ValueError(f"unknown synthetic question {question!r}")
    return samples


def question_specs() -> dict[str, dict]:
    return {
        "queue": {
            "type": "choice",
            "instructions": "Which team should handle this ticket?",
            "criteria": dict(QUEUE_OPTIONS),
        },
        "escalate": {
            "type": "bool",
            "instructions": "Does this message require urgent human attention?",
            "criteria": dict(ESCALATION_OPTIONS),
        },
    }
